name:CI
 on: 
    push:
       branches:
            -mian
    pull_request:
      branches:
           -main

jobs:
     build:
        runs-on:windows-latest

        
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js'16'
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
        npm test
